# Image base
FROM alpine

# Install tools
RUN apk update && apk add --no-cache busybox-extras

# To delete apk to avoid additional installations
RUN apk del apk-tools

# To delete the folder "/etc/apk" to block the access at the repositories
RUN rm -rf /etc/apk

# Create a non-privileged user
RUN adduser -D troubleshooting

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh

# Make the script executable
RUN chown troubleshooting:troubleshooting /entrypoint.sh && chmod +x /entrypoint.sh

# Set the non-privileged user as the default user
USER troubleshooting

# Command to run the entrypoint script by default
ENTRYPOINT ["/entrypoint.sh"]